enum NOTIFICATION_HANDLER_KEYS {
    ACCEPT_CLIENT = " ACCEPT_CLIENT",
    ACCEPT_STATION = "ACCEPT_STATION",
    ASSIGN_STATION_ROLE = "ASSIGN_STATION_ROLE",
}

export const frontendEnums = {
    NOTIFICATION_HANDLER_KEYS
}