export const ImageLut = {
    "avocado_toast": "final/Avocado toast.png",
    "bacon_toast": "final/Bacon toast.png",
    "burger": "final/Burger.png",
    "carrot_stew": "final/Carrot stew.png",
    "cheese": "final/Cheese.png",
    "chocolate_croissant": "final/Chocolate croissant.png",
    "chocolate_doughnut": "final/Chocolate doughnut.png",
    "croissant": "final/Croissant.png",
    "coffee": "final/Cup of coffee.png",
    "tea": "final/Cup of tea.png",
    "egg_toast": "final/Egg toast.png",
    "empty_bowl_1": "final/Empty bowl 1.png",
    "empty_bowl_2": "final/Empty bowl 2.png",
    "empty_cup_1": "final/Empty cup 1.png",
    "empty_cup_2": "final/Empty cup 2.png",
    "jam_doughnut": "final/Jam doughnut.png",
    "jam_pastry": "final/Jam pastrie.png",
    "jam_toast": "final/Jam toast.png",
    "meatballs": "final/Meatballs.png",
    "milk_and_cookies": "final/Milk and cookies.png",
    "mushroom_stew": "final/Mushroom Stew.png",
    "pbj_toast": "final/Peanut butter and jelly toast.png",
    "pistachio_doughnut": "final/Pistachio doughnut.png",
    "pumpkin_soup": "final/Pumpkin soup.png",
    "strawberry_cake": "final/Strawberry cake.png",
    "strawberry_doughnut": "final/Strawberry doughnut.png",
    "toast": "final/Toast.png",
    "tomato_stew": "final/Tomato stew.png"
}
